name: Apptainer Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: comses/setup-apptainer@v2
      with:
        apptainer-version: 1.2.3
    - name: Build apptainer images
      run: make apptainer-build
